// Unit test for decode_unit (CP932 + GBK) against Python-generated vectors.
#include <cstdint>
#include <cstdio>
#include <vector>

// Stubs so host_fonts.cpp links standalone.
void host_log(const char* fmt, ...) {
    (void)fmt;
}
struct w2c_th100x2Dgame;
extern "C" {
uint32_t w2c_th100x2Dgame_graphics_allocate(w2c_th100x2Dgame*, uint32_t) {
    return 0;
}
void w2c_th100x2Dgame_graphics_free(w2c_th100x2Dgame*, uint32_t) {}
}

#include "../src/host_fonts.cpp"

static int failures = 0;
static void check(const std::vector<uint8_t>& bytes, bool gbk,
                  const std::vector<uint32_t>& expect, const char* name) {
    std::vector<uint32_t> got =
        gbk ? decode936(bytes.data(), (uint32_t)bytes.size())
            : decode932(bytes.data(), (uint32_t)bytes.size());
    if (got != expect) {
        failures++;
        printf("FAIL %s: got %u units, want %u\n", name, (unsigned)got.size(),
               (unsigned)expect.size());
        for (size_t i = 0; i < got.size() && i < expect.size(); i++)
            if (got[i] != expect[i]) {
                printf("  [%u] got U+%04X want U+%04X\n", (unsigned)i, got[i],
                       expect[i]);
                break;
            }
    } else {
        printf("ok %s (%u units)\n", name, (unsigned)got.size());
    }
}

int main() {
    // Vectors generated by: python3 tests/gen_vectors.py
    FILE* f = fopen("tests/vectors.bin", "rb");
    if (!f) {
        printf("vectors.bin missing\n");
        return 1;
    }
    uint8_t hdr[8];
    if (fread(hdr, 1, 8, f) != 8) return 1;
    uint32_t ncases = hdr[0] | (hdr[1] << 8) | (hdr[2] << 16) | (hdr[3] << 24);
    for (uint32_t c = 0; c < ncases; c++) {
        uint8_t h[8];
        if (fread(h, 1, 8, f) != 8) return 1;
        bool gbk = h[0] != 0;
        uint32_t nlen = h[1], nbytes = h[2] | (h[3] << 8), nunits = h[4] | (h[5] << 8) | (h[6] << 16) | (h[7] << 24);
        char name[64] = {0};
        if (fread(name, 1, nlen, f) != nlen) return 1;
        std::vector<uint8_t> bytes(nbytes);
        if (nbytes && fread(bytes.data(), 1, nbytes, f) != nbytes) return 1;
        std::vector<uint32_t> expect(nunits);
        for (uint32_t i = 0; i < nunits; i++) {
            uint8_t b[2];
            if (fread(b, 1, 2, f) != 2) return 1;
            expect[i] = b[0] | (b[1] << 8);
        }
        check(bytes, gbk, expect, name);
    }
    fclose(f);
    printf(failures ? "FAILURES: %d\n" : "ALL PASS\n", failures);
    return failures ? 1 : 0;
}
