/* Automatically generated by wasm2c */
#ifndef TH10_WASM_H_GENERATED_
#define TH10_WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_th10__audio;
struct w2c_th10__files;
struct w2c_th10__fonts;
struct w2c_th10__graphics;
struct w2c_th10__time;

typedef struct w2c_th100x2Dgame {
  struct w2c_th10__audio* w2c_th10__audio_instance;
  struct w2c_th10__files* w2c_th10__files_instance;
  struct w2c_th10__fonts* w2c_th10__fonts_instance;
  struct w2c_th10__graphics* w2c_th10__graphics_instance;
  struct w2c_th10__time* w2c_th10__time_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_th100x2Dgame;

void wasm2c_th100x2Dgame_instantiate(w2c_th100x2Dgame*, struct w2c_th10__audio*, struct w2c_th10__files*, struct w2c_th10__fonts*, struct w2c_th10__graphics*, struct w2c_th10__time*);
void wasm2c_th100x2Dgame_free(w2c_th100x2Dgame*);
wasm_rt_func_type_t wasm2c_th100x2Dgame_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'th10_audio' 'advance' */
void w2c_th10__audio_advance(struct w2c_th10__audio*, u32);

/* import: 'th10_audio' 'call' */
u32 w2c_th10__audio_call(struct w2c_th10__audio*, u32, u32, u32);

/* import: 'th10_audio' 'create' */
u32 w2c_th10__audio_create(struct w2c_th10__audio*);

/* import: 'th10_audio' 'event' */
u32 w2c_th10__audio_event(struct w2c_th10__audio*, u32, u32);

/* import: 'th10_files' 'close' */
void w2c_th10__files_close(struct w2c_th10__files*, u32);

/* import: 'th10_files' 'list' */
u32 w2c_th10__files_list(struct w2c_th10__files*, u32, u32, u32, u32, u32);

/* import: 'th10_files' 'open' */
u32 w2c_th10__files_open(struct w2c_th10__files*, u32, u32);

/* import: 'th10_files' 'read' */
u32 w2c_th10__files_read(struct w2c_th10__files*, u32, u32, u32);

/* import: 'th10_files' 'seek' */
u32 w2c_th10__files_seek(struct w2c_th10__files*, u32, u32, u32);

/* import: 'th10_files' 'size' */
u32 w2c_th10__files_size(struct w2c_th10__files*, u32);

/* import: 'th10_files' 'write' */
u32 w2c_th10__files_write(struct w2c_th10__files*, u32, u32, u32);

/* import: 'th10_fonts' 'background' */
void w2c_th10__fonts_background(struct w2c_th10__fonts*, u32, u32);

/* import: 'th10_fonts' 'bitmap' */
u32 w2c_th10__fonts_bitmap(struct w2c_th10__fonts*, u32, u32);

/* import: 'th10_fonts' 'color' */
void w2c_th10__fonts_color(struct w2c_th10__fonts*, u32, u32);

/* import: 'th10_fonts' 'context' */
u32 w2c_th10__fonts_context(struct w2c_th10__fonts*);

/* import: 'th10_fonts' 'delete_context' */
void w2c_th10__fonts_delete_context(struct w2c_th10__fonts*, u32);

/* import: 'th10_fonts' 'delete_object' */
void w2c_th10__fonts_delete_object(struct w2c_th10__fonts*, u32);

/* import: 'th10_fonts' 'font' */
u32 w2c_th10__fonts_font(struct w2c_th10__fonts*, u32, u32, u32);

/* import: 'th10_fonts' 'select' */
u32 w2c_th10__fonts_select(struct w2c_th10__fonts*, u32, u32);

/* import: 'th10_fonts' 'text' */
void w2c_th10__fonts_text(struct w2c_th10__fonts*, u32, u32, u32, u32, u32);

/* import: 'th10_graphics' 'create' */
u32 w2c_th10__graphics_create(struct w2c_th10__graphics*, u32, u32);

/* import: 'th10_graphics' 'device' */
u32 w2c_th10__graphics_device(struct w2c_th10__graphics*, u32, u32, u32);

/* import: 'th10_graphics' 'resource' */
u32 w2c_th10__graphics_resource(struct w2c_th10__graphics*, u32, u32, u32);

/* import: 'th10_time' 'local_date' */
void w2c_th10__time_local_date(struct w2c_th10__time*, u32, u32);

/* import: 'th10_time' 'monotonic' */
f64 w2c_th10__time_monotonic(struct w2c_th10__time*);

/* import: 'th10_time' 'timestamp' */
u32 w2c_th10__time_timestamp(struct w2c_th10__time*);

/* export: 'memory' */
wasm_rt_memory_t* w2c_th100x2Dgame_memory(w2c_th100x2Dgame* instance);

/* export: 'animation_engine_create' */
u32 w2c_th100x2Dgame_animation_engine_create(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'animation_engine_destroy' */
void w2c_th100x2Dgame_animation_engine_destroy(w2c_th100x2Dgame*, u32);

/* export: 'animation_engine_manager' */
u32 w2c_th100x2Dgame_animation_engine_manager(w2c_th100x2Dgame*, u32);

/* export: 'animation_engine_camera' */
u32 w2c_th100x2Dgame_animation_engine_camera(w2c_th100x2Dgame*, u32, u32);

/* export: 'animation_engine_load' */
u32 w2c_th100x2Dgame_animation_engine_load(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'animation_engine_unload' */
void w2c_th100x2Dgame_animation_engine_unload(w2c_th100x2Dgame*, u32, u32);

/* export: 'animation_engine_spawn' */
u32 w2c_th100x2Dgame_animation_engine_spawn(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'animation_engine_find' */
u32 w2c_th100x2Dgame_animation_engine_find(w2c_th100x2Dgame*, u32, u32);

/* export: 'animation_engine_update' */
u32 w2c_th100x2Dgame_animation_engine_update(w2c_th100x2Dgame*, u32);

/* export: 'animation_engine_draw' */
u32 w2c_th100x2Dgame_animation_engine_draw(w2c_th100x2Dgame*, u32);

/* export: 'animation_engine_interrupt' */
void w2c_th100x2Dgame_animation_engine_interrupt(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'animation_engine_remove_all' */
void w2c_th100x2Dgame_animation_engine_remove_all(w2c_th100x2Dgame*, u32);

/* export: 'application_create' */
u32 w2c_th100x2Dgame_application_create(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'application_destroy' */
void w2c_th100x2Dgame_application_destroy(w2c_th100x2Dgame*, u32);

/* export: 'application_step' */
u32 w2c_th100x2Dgame_application_step(w2c_th100x2Dgame*, u32);

/* export: 'application_delay' */
f64 w2c_th100x2Dgame_application_delay(w2c_th100x2Dgame*, u32);

/* export: 'application_save' */
void w2c_th100x2Dgame_application_save(w2c_th100x2Dgame*, u32);

/* export: 'application_error' */
u32 w2c_th100x2Dgame_application_error(w2c_th100x2Dgame*, u32);

/* export: 'application_state' */
u32 w2c_th100x2Dgame_application_state(w2c_th100x2Dgame*, u32);

/* export: 'application_statistics' */
u32 w2c_th100x2Dgame_application_statistics(w2c_th100x2Dgame*, u32);

/* export: 'application_world' */
u32 w2c_th100x2Dgame_application_world(w2c_th100x2Dgame*, u32);

/* export: 'application_title' */
u32 w2c_th100x2Dgame_application_title(w2c_th100x2Dgame*, u32);

/* export: 'application_ending' */
u32 w2c_th100x2Dgame_application_ending(w2c_th100x2Dgame*, u32);

/* export: 'application_startup' */
u32 w2c_th100x2Dgame_application_startup(w2c_th100x2Dgame*, u32);

/* export: 'application_stop' */
void w2c_th100x2Dgame_application_stop(w2c_th100x2Dgame*, u32);

/* export: 'application_touch_state' */
void w2c_th100x2Dgame_application_touch_state(w2c_th100x2Dgame*, u32, u32);

/* export: 'audio_create' */
u32 w2c_th100x2Dgame_audio_create(w2c_th100x2Dgame*, u32);

/* export: 'audio_destroy' */
void w2c_th100x2Dgame_audio_destroy(w2c_th100x2Dgame*, u32);

/* export: 'audio_initialize' */
u32 w2c_th100x2Dgame_audio_initialize(w2c_th100x2Dgame*, u32, u32);

/* export: 'audio_manager' */
u32 w2c_th100x2Dgame_audio_manager(w2c_th100x2Dgame*, u32);

/* export: 'audio_configure' */
void w2c_th100x2Dgame_audio_configure(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32);

/* export: 'audio_formats' */
u32 w2c_th100x2Dgame_audio_formats(w2c_th100x2Dgame*, u32, u32);

/* export: 'audio_start_file' */
u32 w2c_th100x2Dgame_audio_start_file(w2c_th100x2Dgame*, u32, u32);

/* export: 'audio_update' */
u32 w2c_th100x2Dgame_audio_update(w2c_th100x2Dgame*, u32);

/* export: 'audio_advance' */
void w2c_th100x2Dgame_audio_advance(w2c_th100x2Dgame*, u32, u32);

/* export: 'audio_fades' */
void w2c_th100x2Dgame_audio_fades(w2c_th100x2Dgame*, u32);

/* export: 'audio_queue_effect' */
void w2c_th100x2Dgame_audio_queue_effect(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'audio_queue_music' */
void w2c_th100x2Dgame_audio_queue_music(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'audio_stream_operation' */
u32 w2c_th100x2Dgame_audio_stream_operation(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'audio_tasks' */
u32 w2c_th100x2Dgame_audio_tasks(w2c_th100x2Dgame*, u32);

/* export: 'audio_call' */
u32 w2c_th100x2Dgame_audio_call(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'backgrounds_create' */
u32 w2c_th100x2Dgame_backgrounds_create(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'backgrounds_destroy' */
void w2c_th100x2Dgame_backgrounds_destroy(w2c_th100x2Dgame*, u32);

/* export: 'backgrounds_load' */
u32 w2c_th100x2Dgame_backgrounds_load(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'backgrounds_release' */
void w2c_th100x2Dgame_backgrounds_release(w2c_th100x2Dgame*, u32, u32);

/* export: 'backgrounds_activate' */
void w2c_th100x2Dgame_backgrounds_activate(w2c_th100x2Dgame*, u32);

/* export: 'backgrounds_restart' */
void w2c_th100x2Dgame_backgrounds_restart(w2c_th100x2Dgame*, u32, u32);

/* export: 'backgrounds_effect' */
void w2c_th100x2Dgame_backgrounds_effect(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'captures_create' */
u32 w2c_th100x2Dgame_captures_create(w2c_th100x2Dgame*, u32);

/* export: 'captures_destroy' */
void w2c_th100x2Dgame_captures_destroy(w2c_th100x2Dgame*, u32);

/* export: 'captures_process' */
void w2c_th100x2Dgame_captures_process(w2c_th100x2Dgame*, u32);

/* export: 'captures_copy_surface' */
u32 w2c_th100x2Dgame_captures_copy_surface(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32);

/* export: 'common_create' */
u32 w2c_th100x2Dgame_common_create(w2c_th100x2Dgame*, u32);

/* export: 'common_destroy' */
void w2c_th100x2Dgame_common_destroy(w2c_th100x2Dgame*, u32);

/* export: 'common_state' */
u32 w2c_th100x2Dgame_common_state(w2c_th100x2Dgame*, u32);

/* export: 'common_enable' */
void w2c_th100x2Dgame_common_enable(w2c_th100x2Dgame*, u32);

/* export: 'common_queue' */
void w2c_th100x2Dgame_common_queue(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'common_small' */
void w2c_th100x2Dgame_common_small(w2c_th100x2Dgame*, u32);

/* export: 'common_draw' */
u32 w2c_th100x2Dgame_common_draw(w2c_th100x2Dgame*, u32, u32);

/* export: 'credits_create' */
u32 w2c_th100x2Dgame_credits_create(w2c_th100x2Dgame*, u32, u32);

/* export: 'credits_destroy' */
void w2c_th100x2Dgame_credits_destroy(w2c_th100x2Dgame*, u32);

/* export: 'credits_advance_loading' */
void w2c_th100x2Dgame_credits_advance_loading(w2c_th100x2Dgame*, u32);

/* export: 'credits_value' */
u32 w2c_th100x2Dgame_credits_value(w2c_th100x2Dgame*, u32);

/* export: 'credits_error' */
u32 w2c_th100x2Dgame_credits_error(w2c_th100x2Dgame*, u32);

/* export: 'files_allocate' */
u32 w2c_th100x2Dgame_files_allocate(w2c_th100x2Dgame*, u32);

/* export: 'files_free' */
void w2c_th100x2Dgame_files_free(w2c_th100x2Dgame*, u32);

/* export: 'files_create' */
u32 w2c_th100x2Dgame_files_create(w2c_th100x2Dgame*);

/* export: 'files_destroy' */
void w2c_th100x2Dgame_files_destroy(w2c_th100x2Dgame*, u32);

/* export: 'files_attach' */
u32 w2c_th100x2Dgame_files_attach(w2c_th100x2Dgame*, u32, u32);

/* export: 'files_count' */
u32 w2c_th100x2Dgame_files_count(w2c_th100x2Dgame*, u32);

/* export: 'files_name' */
u32 w2c_th100x2Dgame_files_name(w2c_th100x2Dgame*, u32, u32);

/* export: 'files_size' */
u32 w2c_th100x2Dgame_files_size(w2c_th100x2Dgame*, u32, u32);

/* export: 'files_load' */
u32 w2c_th100x2Dgame_files_load(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'files_save' */
u32 w2c_th100x2Dgame_files_save(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'files_lock_depth' */
u32 w2c_th100x2Dgame_files_lock_depth(w2c_th100x2Dgame*, u32);

/* export: 'fonts_create' */
u32 w2c_th100x2Dgame_fonts_create(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'fonts_destroy' */
void w2c_th100x2Dgame_fonts_destroy(w2c_th100x2Dgame*, u32);

/* export: 'fonts_draw' */
void w2c_th100x2Dgame_fonts_draw(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'fonts_draw_animation' */
void w2c_th100x2Dgame_fonts_draw_animation(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'fonts_bitmap' */
u32 w2c_th100x2Dgame_fonts_bitmap(w2c_th100x2Dgame*, u32);

/* export: 'game_state_create' */
u32 w2c_th100x2Dgame_game_state_create(w2c_th100x2Dgame*, u32, u32);

/* export: 'game_state_destroy' */
void w2c_th100x2Dgame_game_state_destroy(w2c_th100x2Dgame*, u32);

/* export: 'game_state_economy' */
u32 w2c_th100x2Dgame_game_state_economy(w2c_th100x2Dgame*, u32);

/* export: 'game_state_configuration' */
u32 w2c_th100x2Dgame_game_state_configuration(w2c_th100x2Dgame*, u32);

/* export: 'game_state_pending' */
u32 w2c_th100x2Dgame_game_state_pending(w2c_th100x2Dgame*, u32);

/* export: 'graphics_allocate' */
u32 w2c_th100x2Dgame_graphics_allocate(w2c_th100x2Dgame*, u32);

/* export: 'graphics_free' */
void w2c_th100x2Dgame_graphics_free(w2c_th100x2Dgame*, u32);

/* export: 'graphics_configure_arithmetic' */
void w2c_th100x2Dgame_graphics_configure_arithmetic(w2c_th100x2Dgame*, u32);

/* export: 'graphics_arithmetic_mode' */
void w2c_th100x2Dgame_graphics_arithmetic_mode(w2c_th100x2Dgame*, u32, u32);

/* export: 'graphics_create' */
u32 w2c_th100x2Dgame_graphics_create(w2c_th100x2Dgame*, u32, u32);

/* export: 'graphics_destroy' */
void w2c_th100x2Dgame_graphics_destroy(w2c_th100x2Dgame*, u32);

/* export: 'graphics_device' */
u32 w2c_th100x2Dgame_graphics_device(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'graphics_resource' */
u32 w2c_th100x2Dgame_graphics_resource(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'graphics_draw' */
u32 w2c_th100x2Dgame_graphics_draw(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'graphics_camera' */
void w2c_th100x2Dgame_graphics_camera(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32);

/* export: 'input_create' */
u32 w2c_th100x2Dgame_input_create(w2c_th100x2Dgame*);

/* export: 'input_destroy' */
void w2c_th100x2Dgame_input_destroy(w2c_th100x2Dgame*, u32);

/* export: 'input_snapshot' */
u32 w2c_th100x2Dgame_input_snapshot(w2c_th100x2Dgame*, u32);

/* export: 'input_profiles' */
u32 w2c_th100x2Dgame_input_profiles(w2c_th100x2Dgame*, u32);

/* export: 'input_configure' */
void w2c_th100x2Dgame_input_configure(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'input_sample' */
u32 w2c_th100x2Dgame_input_sample(w2c_th100x2Dgame*, u32);

/* export: 'input_update' */
void w2c_th100x2Dgame_input_update(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'input_buttons' */
u32 w2c_th100x2Dgame_input_buttons(w2c_th100x2Dgame*, u32, u32);

/* export: 'input_release_keys' */
void w2c_th100x2Dgame_input_release_keys(w2c_th100x2Dgame*, u32);

/* export: 'replay_document_create' */
u32 w2c_th100x2Dgame_replay_document_create(w2c_th100x2Dgame*, u32, u32);

/* export: 'replay_document_destroy' */
void w2c_th100x2Dgame_replay_document_destroy(w2c_th100x2Dgame*, u32);

/* export: 'replay_document_load' */
u32 w2c_th100x2Dgame_replay_document_load(w2c_th100x2Dgame*, u32, u32);

/* export: 'replay_document_value' */
u32 w2c_th100x2Dgame_replay_document_value(w2c_th100x2Dgame*, u32);

/* export: 'replay_document_allocate' */
u32 w2c_th100x2Dgame_replay_document_allocate(w2c_th100x2Dgame*, u32, u32);

/* export: 'replay_document_allocations' */
u32 w2c_th100x2Dgame_replay_document_allocations(w2c_th100x2Dgame*, u32);

/* export: 'replay_writer_create' */
u32 w2c_th100x2Dgame_replay_writer_create(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'replay_writer_destroy' */
void w2c_th100x2Dgame_replay_writer_destroy(w2c_th100x2Dgame*, u32);

/* export: 'replay_writer_save' */
u32 w2c_th100x2Dgame_replay_writer_save(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'replay_writer_allocations' */
u32 w2c_th100x2Dgame_replay_writer_allocations(w2c_th100x2Dgame*, u32);

/* export: 'scores_create' */
u32 w2c_th100x2Dgame_scores_create(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'scores_destroy' */
void w2c_th100x2Dgame_scores_destroy(w2c_th100x2Dgame*, u32);

/* export: 'scores_data' */
u32 w2c_th100x2Dgame_scores_data(w2c_th100x2Dgame*, u32);

/* export: 'scores_save' */
u32 w2c_th100x2Dgame_scores_save(w2c_th100x2Dgame*, u32);

/* export: 'scores_reload' */
void w2c_th100x2Dgame_scores_reload(w2c_th100x2Dgame*, u32);

/* export: 'scores_allocations' */
u32 w2c_th100x2Dgame_scores_allocations(w2c_th100x2Dgame*, u32);

/* export: 'effects_create' */
u32 w2c_th100x2Dgame_effects_create(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'effects_destroy' */
void w2c_th100x2Dgame_effects_destroy(w2c_th100x2Dgame*, u32);

/* export: 'effects_start' */
u32 w2c_th100x2Dgame_effects_start(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'effects_fade_out' */
void w2c_th100x2Dgame_effects_fade_out(w2c_th100x2Dgame*, u32, u32);

/* export: 'effects_count' */
u32 w2c_th100x2Dgame_effects_count(w2c_th100x2Dgame*, u32);

/* export: 'effects_remove' */
void w2c_th100x2Dgame_effects_remove(w2c_th100x2Dgame*, u32, u32);

/* export: 'startup_create' */
u32 w2c_th100x2Dgame_startup_create(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'startup_destroy' */
void w2c_th100x2Dgame_startup_destroy(w2c_th100x2Dgame*, u32);

/* export: 'startup_advance_loading' */
void w2c_th100x2Dgame_startup_advance_loading(w2c_th100x2Dgame*, u32);

/* export: 'startup_value' */
u32 w2c_th100x2Dgame_startup_value(w2c_th100x2Dgame*, u32);

/* export: 'startup_common' */
u32 w2c_th100x2Dgame_startup_common(w2c_th100x2Dgame*, u32);

/* export: 'startup_scores' */
u32 w2c_th100x2Dgame_startup_scores(w2c_th100x2Dgame*, u32);

/* export: 'startup_error' */
u32 w2c_th100x2Dgame_startup_error(w2c_th100x2Dgame*, u32);

/* export: 'text_format' */
u32 w2c_th100x2Dgame_text_format(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'textures_filter_table' */
u32 w2c_th100x2Dgame_textures_filter_table(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'textures_resample' */
u32 w2c_th100x2Dgame_textures_resample(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'textures_copy_pixels' */
u32 w2c_th100x2Dgame_textures_copy_pixels(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32);

/* export: 'textures_embedded' */
u32 w2c_th100x2Dgame_textures_embedded(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'textures_empty' */
u32 w2c_th100x2Dgame_textures_empty(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32);

/* export: 'animations_create' */
u32 w2c_th100x2Dgame_animations_create(w2c_th100x2Dgame*, u32, u32, u32, u32);

/* export: 'animations_destroy' */
void w2c_th100x2Dgame_animations_destroy(w2c_th100x2Dgame*, u32);

/* export: 'animations_load' */
u32 w2c_th100x2Dgame_animations_load(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'animations_unload' */
void w2c_th100x2Dgame_animations_unload(w2c_th100x2Dgame*, u32, u32);

/* export: 'animations_error' */
u32 w2c_th100x2Dgame_animations_error(w2c_th100x2Dgame*, u32);

/* export: 'title_create' */
u32 w2c_th100x2Dgame_title_create(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'title_destroy' */
void w2c_th100x2Dgame_title_destroy(w2c_th100x2Dgame*, u32);

/* export: 'title_value' */
u32 w2c_th100x2Dgame_title_value(w2c_th100x2Dgame*, u32);

/* export: 'title_advance_loading' */
void w2c_th100x2Dgame_title_advance_loading(w2c_th100x2Dgame*, u32);

/* export: 'title_input' */
void w2c_th100x2Dgame_title_input(w2c_th100x2Dgame*, u32, u32);

/* export: 'title_create_from_startup' */
u32 w2c_th100x2Dgame_title_create_from_startup(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'world_create' */
u32 w2c_th100x2Dgame_world_create(w2c_th100x2Dgame*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'world_destroy' */
void w2c_th100x2Dgame_world_destroy(w2c_th100x2Dgame*, u32);

/* export: 'world_start' */
u32 w2c_th100x2Dgame_world_start(w2c_th100x2Dgame*, u32, u32, u32);

/* export: 'world_select_stage' */
u32 w2c_th100x2Dgame_world_select_stage(w2c_th100x2Dgame*, u32, u32, u32, u32, u32);

/* export: 'world_input' */
void w2c_th100x2Dgame_world_input(w2c_th100x2Dgame*, u32, u32);

/* export: 'world_advance_loading' */
void w2c_th100x2Dgame_world_advance_loading(w2c_th100x2Dgame*, u32);

/* export: 'world_stop' */
void w2c_th100x2Dgame_world_stop(w2c_th100x2Dgame*, u32);

/* export: 'world_error' */
u32 w2c_th100x2Dgame_world_error(w2c_th100x2Dgame*, u32);

/* export: 'world_actor' */
u32 w2c_th100x2Dgame_world_actor(w2c_th100x2Dgame*, u32, u32);

/* export: 'world_frame_timing' */
void w2c_th100x2Dgame_world_frame_timing(w2c_th100x2Dgame*, u32, f32, f64, f64);

/* export: 'world_bind_title' */
void w2c_th100x2Dgame_world_bind_title(w2c_th100x2Dgame*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* TH10_WASM_H_GENERATED_ */
